### ISSUE TITLE
Cannot disable iPhone X Gestures

### ISSUE THREAD

**Issue by haloteanix** [c22dev/TrollBox#10]
When you enable it, respring, and go back, it shows that the gestures are off but it's still on. I had to reset my entire iPhone to remove it.

**Comment by c22dev** [comment]
Hey ! Before resetting you’re phone, contact me. Did you experienced any errors ? Did you respringed after disabling ? For me on iPhone SE1 it works

**Comment by haloteanix** [comment]
I see my icons (not the widgets) being a bit more spaced out from each other, the floating dock taking up almost all of the space at the bottom, the status bar got replaced with a red bar with the text "😳 id:[random numbers]". And here's the thing: when I go in normal mode (not jailbroken), it's still there.

At the end I just reset my iPhone and everything went back to normal.

**Comment by c22dev** [comment]
You shouldn’t have reset you’re phone, you just had to contact me. What’s you’re device and version for me to test ?

**Comment by haloteanix** [comment]
iPhone 8 Plus with iOS 16.1.2 (palera1n Jailbreak). I reset my phone anyways.

**Comment by c22dev** [comment]
Open Filza 
Go to /var/containers/Shared/SystemGroup/systemgroup.com.apple.mobilegestaltcache/Library/Caches and open the com.apple.MobileGestalt.plist. Open CacheExtra and search for a Dictionary that begins with oPeik, and finally find the ArtworkDeviceSubType

Copy this for iPhone 8+:
570
Copy this for anything else :
569
