### ISSUE TITLE
Cannot disable HOME GESTURE

### ISSUE THREAD

**Issue by rishard456** [c22dev/TrollBox#15]
I cannot apply changes on HOME GUESTURE disabled status

**Comment by haloteanix** [comment]
I had the same problem. What I did was reset my device and it was back to normal. But the creator of this repository can tell you another way to do so.

**Comment by c22dev** [comment]
Hey, 
Open Filza
Go to /var/containers/Shared/SystemGroup/systemgroup.com.apple.mobilegestaltcache/Library/Caches and open the com.apple.MobileGestalt.plist. Open CacheExtra and search for a Dictionary that begins with oPeik, and finally find the ArtworkDeviceSubType

Copy this for iPhone 8+:
570
Copy this for anything else (not for iPads !):
569
Hope this helps !
