### ISSUE TITLE
Air Spammer

### ISSUE THREAD

**Issue by Mora140** [c22dev/TrollBox#19]
After respring Air SPAMMER Tab disappeared, and I can't get it back

**Comment by c22dev** [comment]
Hey. Can you provide some more information ? 
- What iOS Version are you on ?
- What type of TrollBox did you used (TrollBox16 or TrollBox.tipa) ?
- Did you tried using a different type if you're on TrollStore ?

Thanks, I hope we can fix this issue.

**Comment by Mora140** [comment]
Hello, iphone 11 pro 16.0
I'm using trollbox16 and I didn't tried another version

**Comment by c22dev** [comment]
It’s normal as there is no AirSpammer for iOS 16.
