### ISSUE TITLE
Locsim doesn't work

### ISSUE THREAD

**Issue by k3v1nwrld** [c22dev/TrollBox#2]
It either crashes the app or just doesn't do anything. Also you can't use the map, I had to input the coordinates myself

**Comment by c22dev** [comment]
Hey ! For me it works fine. At the moment, the app is in alpha, so you need to put you’re coordinate by yourself… sorry. What’s your device/version ?

**Comment by c22dev** [comment]
Do you see a purple dot on the map ?

**Comment by k3v1nwrld** [comment]
I have an 11 pro on 15.0.2, and no I don't see any purple dot on the map. Also the app crashes only if there are comas or letters, if it has only numbers it wont do anything

**Comment by c22dev** [comment]
Can you try putting 12 and 13 ? It should give you this result after pressing Apply 
![(example)](https://user-images.githubusercontent.com/102235607/209418483-ec2657ca-9419-43d3-8fa5-5694912e72e6.png)
It works fine for me then 
![(example)](https://user-images.githubusercontent.com/102235607/209418505-6e4f2fa0-ec10-4cda-9a1c-4f05071bc09d.png)

**Comment by k3v1nwrld** [comment]
It works with those coordinates now, maybe it's just me getting wrong coordinates from maps app. Where do you get ur coordinates from?

**Comment by c22dev** [comment]
Try https://www.latlong.net/
