### ISSUE TITLE
Sandbox Problem

### ISSUE THREAD

**Issue by Sw1per-alt** [c22dev/TrollBox#21]
After I download the ipa and open the app it says thisb[![image](https://user-images.githubusercontent.com/117046958/215452840-ae644ebf-443b-40f7-8577-bd1cdb628170.png)]() that it has to force close and that sandbox was somehow disabled.

**Comment by c22dev** [comment]
Restart the app :)

**Comment by c22dev** [comment]
Uh excuse me what iOS version do you have ?

**Comment by tkiengarrixer** [comment]
15.6 RC

**Comment by tkiengarrixer** [comment]
Please update Zhuowei's code to solve this problem

**Comment by c22dev** [comment]
It’s up to date

**Comment by tkiengarrixer** [comment]
Not working

**Comment by c22dev** [comment]
It’s working on my side on this version. Provide more information please

**Comment by c22dev** [comment]
I'll close this issue as you're not responding and giving more details. If you think that my code is outdated (it's not), fork it and build it with your modifications and feel free to pull request. It's open-source.
