### ISSUE TITLE
[Bug] Disable Shortcuts banner not working (XSM/15.3.1)

### ISSUE THREAD

**Issue by qnblackcat** [c22dev/TrollBox#22]
### Spec:
- Device model: iPhones XSM
- iOS: 15.3.1
- TrollBox: v0.1
- Sideload tool: TrollStore v1.5.0

### Describe the issue:
As I said in the title, the option to disable Shortcuts banner is not working correctly when my automation was launched. The banner keeps showing up like nothing was changed.

**Comment by fasiltahr** [comment]
> ### Spec:
> 
> - Device model: iPhones XSM
> 
> - iOS: 15.3.1
> 
> - TrollBox: v0.1
> 
> - Sideload tool: TrollStore v1.5.0
> 
> 
> 
> ### Describe the issue:
> 
> As I said in the title, the option to disable Shortcuts banner is not working correctly when my automation was launched. The banner keeps showing up like nothing was changed.

**Comment by c22dev** [comment]
I will attempt to fix this in next version

**Comment by fasiltahr** [comment]
> I will attempt to fix this in next version

**Comment by c22dev** [comment]
Sadly, I won't implement this fix on version 0.2. But if you really want to disable them, go to /var/mobile/Library/WebClips in the file explorer of your choice. Open the folder with the right webclip(s) that you made. Open the .plist file placed there, the remove the "ShortcutIdentifier" string from the plist. And finally, you can do a reboot or a respring. Next beta versions will maybe have this feature.
