### ISSUE TITLE
Spoofed location will revert to real location after X hours

### ISSUE THREAD

**Issue by albertklcheung** [c22dev/TrollBox#24]
Hello,

2 questions here:
1) Are there any way to make spoofed location more persistent? It looks like that it will revert to real location after X hours
2) Will you consider implementing a bookmark feature so that I don't need to enter coordinates every time.

Thank you and keep up the good work!

Albert

**Comment by c22dev** [comment]
This is completely normal. A classic localisation changer also do that. I can fix it, because I’m actually implementing a background refreshing feature. I might also add a bookmark system in the future.

**Comment by albertklcheung** [comment]
Thank you! Cannot wait to see these 2 features implemented especially for the background refresh feature. Keep it up!
