### ISSUE TITLE
Update??

### ISSUE THREAD

**Issue by k3v1nwrld** [c22dev/TrollBox#28]
Are there any updates being made?? I saw some commits were made, but no updates on .ipa/.tipa

**Comment by c22dev** [comment]
Join the discord server, and go into [#announcements](https://discord.com/channels/1057381151620218931/1057381686708543578) to download the file from [this message](https://discord.com/channels/1057381151620218931/1057381686708543578/1086457042065170463) :)
[https://discord.gg/8gMyK6DSnB](https://discord.gg/8gMyK6DSnB)
