### ISSUE TITLE
LocSim not working as expected on iOS 17.0.0?

### ISSUE THREAD

**Issue by NotADevBtw** [c22dev/TrollBox#35]
I decided to try out LocSim since it seems to be supported on iOS 17.0.0 with TrollStore, setting the location seems to work but trying to reset it back causes the location to be bugged as if it’s set as a non-precise location, maps seems to display the non-precise location and other apps as well, and no matter what I do precise location doesn’t seem to work, is this a known issue or am I doing something wrong?
(I won’t be including images for privacy reasons but if needed I will)

Device/software info if needed:
iPhone XS on iOS 17.0.0
TrollBox 0.2 installed with TrollStore 2.0.8

**Comment by NotADevBtw** [comment]
Also seems like resetting location & privacy in settings seems to fix this but I’m not sure about it and what causes it.

**Comment by c22dev** [comment]
Hi !
This is a known issue. Some devices acts wrong with location simulation cancelling. 
Please try rebooting your device, it should reset.
Even without rebooting, after a few hours, it should be back to normal.

**Comment by NotADevBtw** [comment]
First thing I did was reboot but that didn’t seem to do anything, but I didn’t wait and see if it would reset so that’s something to note, I guess the only method to reset on command is through resetting location & privacy settings I guess.
Also is a fix planned for this or is it a stock bug?

**Comment by c22dev** [comment]
No, it's not the only method. Rebooting a few times fix the issue. It fixed it for everyone who had the same issue as you.
This is a stock, daemon bug.

**Comment by NotADevBtw** [comment]
Ah makes sense, I only tried rebooting twice so that might be why, so in theory using LocSim is 100% safe on iOS 17? And just to make sure, is bookmarks working? I tried bookmarking a location but it didn’t seem to do anything (with some “lag” when the keyboard is showing up/going down)

**Comment by NotADevBtw** [comment]
I see, thanks for the info, guess the issue can be closed now (or maybe keep it open until the issue is resolved but that’s up to you)
