### ISSUE TITLE
Apple Pay Card Custom Image crash

### ISSUE THREAD

**Issue by gsjv2** [c22dev/TrollBox#4]
App crashes when selecting option
iPhone 13 mini 15.1.1

**Comment by c22dev** [comment]
Can you make a screen recording please ? Thanks.

**Comment by gsjv2** [comment]
There is no error, just the app crashes and you are just on the springboard. This happens when tapping Apple Pay Card custom image

**Comment by c22dev** [comment]
Oh, this looks strange. Have you tried using the official Cardio app (mentionned in the credit section)?

**Comment by gsjv2** [comment]
No, I will try Cardio, but I can’t even access the credit section.  App crashes to springboard as soon as you tap on Apple Pay Card custom image

**Comment by gsjv2** [comment]
Cardio crashes on launch

**Comment by c22dev** [comment]
So there is definitely something wrong. Try reporting the issue to cardio owner.
