### ISSUE TITLE
[Enhancement] Icon missing

### ISSUE THREAD

**Issue by CySxL** [c22dev/TrollBox#7]
The icon of Passcode Themer, AirSpam, LocSim are missed.

![image](https://user-images.githubusercontent.com/15531137/209609947-61a81345-bb58-477a-a638-7c23d9a06c85.jpeg)

**Comment by c22dev** [comment]
What phone are you using ? It looks good on my notched device…
![338ACF89-963E-434B-9F0A-2FABDFF9B802](https://user-images.githubusercontent.com/102235607/209655652-589391ee-bb16-495f-99fd-e0e59719de5d.png)

**Comment by CySxL** [comment]
> What phone are you using ? It looks good on my notched device…
> 
> ![338ACF89-963E-434B-9F0A-2FABDFF9B802](https://user-images.githubusercontent.com/102235607/209655652-589391ee-bb16-495f-99fd-e0e59719de5d.png)
> 
> 

Weird haha. I'm use 11 Pro Max on iOS 14.8 with unc0ver

**Comment by c22dev** [comment]
I'm currently downloading iOS 14.8 simulator on my Mac to test it out.

**Comment by c22dev** [comment]
fixed in 0.0.8
