### ISSUE TITLE
[Enhancement] Drop pin (& pin history) in LocSim

### ISSUE THREAD

**Issue by Zthrowaway** [c22dev/TrollBox#8]
A version of LocSim (called LocaSim) has a map (like TrollBox) and a history/added pins tab as well. This enhancement would allow users to tap and hold a location in the map that can be used to start location simulation. I guess as another enhancement, adding a menu/checklist button on the top right to show previous dropped pins.

Also, thanks for making this :)

**Comment by c22dev** [comment]
Hey, thanks for you’re suggestion. This will maybe be added in 0.0.9 (when all the promised features get added), I’m already working on it.

**Comment by carolynsteeves1** [comment]
could you try make like an speedometer or something like we can walk / drive an route with the location changer?

**Comment by c22dev** [comment]
Like a Location that move if you move from your original location ? Not for 0.0.9, sadly, but maybe later ! I'm currently implementing the original feature you've requested.
